/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackController: typeof import('./src/components/BackController/index.vue')['default']
    BackStars: typeof import('./src/components/BackStars/index.vue')['default']
    BackToTop: typeof import('./src/components/BackToTop/index.vue')['default']
    CollectionTabs: typeof import('./src/components/CollectionTabs/index.vue')['default']
    CrystalLogo: typeof import('./src/components/CrystalLogo/index.vue')['default']
    CursorMove: typeof import('./src/components/CursorMove/index.vue')['default']
    DetailPageHeader: typeof import('./src/components/DetailPageHeader/index.vue')['default']
    DetailSectionHeader: typeof import('./src/components/DetailSectionHeader/index.vue')['default']
    DetailSections: typeof import('./src/components/DetailSections/index.vue')['default']
    DiamondCloseBtn: typeof import('./src/components/DiamondCloseBtn/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FilterRail: typeof import('./src/components/FilterRail/index.vue')['default']
    FooterCom: typeof import('./src/components/FooterCom/index.vue')['default']
    ImageLogAlbumCard: typeof import('./src/components/ImageLogAlbumCard/index.vue')['default']
    IslandClock: typeof import('./src/components/IslandClock/index.vue')['default']
    JourneyVideoPlayer: typeof import('./src/components/JourneyVideoPlayer/index.vue')['default']
    Logo: typeof import('./src/components/Logo/index.vue')['default']
    Logo_rotating3D: typeof import('./src/components/Logo_rotating3D/index.vue')['default']
    LogoOnly3D: typeof import('./src/components/LogoOnly3D/index.vue')['default']
    MarqueeShowcase: typeof import('./src/components/MarqueeShowcase/index.vue')['default']
    MediaGallery: typeof import('./src/components/MediaGallery/index.vue')['default']
    MerchCollectionCard: typeof import('./src/components/MerchCollectionCard/index.vue')['default']
    ModalWrapper: typeof import('./src/components/ModalWrapper/index.vue')['default']
    PageFooter: typeof import('./src/components/PageFooter/index.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sections: typeof import('./src/components/Sections/index.vue')['default']
    ShareButton: typeof import('./src/components/ShareButton/index.vue')['default']
    StartAnimation: typeof import('./src/components/StartAnimation/index.vue')['default']
    ToolCard: typeof import('./src/components/ToolCard/index.vue')['default']
    ToolCrystalLogo: typeof import('./src/components/ToolCrystalLogo/index.vue')['default']
    ToolHeaderActions: typeof import('./src/components/ToolHeaderActions/index.vue')['default']
    ToolPageLayout: typeof import('./src/components/ToolPageLayout/index.vue')['default']
    TypedText: typeof import('./src/components/TypedText/index.vue')['default']
    VlogCard: typeof import('./src/components/VlogCard/index.vue')['default']
    WorkCard: typeof import('./src/components/WorkCard/index.vue')['default']
    WorkDetailModal: typeof import('./src/components/WorkDetailModal/index.vue')['default']
  }
}
