/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackController: typeof import('./src/components/BackController/index.vue')['default']
    BackStars: typeof import('./src/components/BackStars/index.vue')['default']
    CrystalLogo: typeof import('./src/components/CrystalLogo/index.vue')['default']
    CursorMove: typeof import('./src/components/CursorMove/index.vue')['default']
    DiamondCloseBtn: typeof import('./src/components/DiamondCloseBtn/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FooterCom: typeof import('./src/components/FooterCom/index.vue')['default']
    Logo: typeof import('./src/components/Logo/index.vue')['default']
    Logo_rotating3D: typeof import('./src/components/Logo_rotating3D/index.vue')['default']
    LogoOnly3D: typeof import('./src/components/LogoOnly3D/index.vue')['default']
    MarqueeShowcase: typeof import('./src/components/MarqueeShowcase/index.vue')['default']
    ModalWrapper: typeof import('./src/components/ModalWrapper/index.vue')['default']
    PageFooter: typeof import('./src/components/PageFooter/index.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartAnimation: typeof import('./src/components/StartAnimation/index.vue')['default']
  }
}
