"""Preserve the entire source cmap while producing lazy-loaded Unicode shards."""

import hashlib
import json
import shutil
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "scripts/fonts/UnboundedSans-Regular.ttf"
OUTPUT = ROOT / "scripts/fonts/generated"
STYLESHEET = ROOT / "src/assets/style/fonts/unbounded.generated.less"


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def unicode_ranges(points):
    """Exact ranges avoid overlapping faces and unnecessary shard downloads."""
    ranges = []
    start = end = points[0]
    for point in points[1:]:
        if point == end + 1:
            end = point
        else:
            ranges.append((start, end))
            start = end = point
    ranges.append((start, end))
    return ", ".join(
        f"U+{start:04X}" if start == end else f"U+{start:04X}-{end:04X}"
        for start, end in ranges
    )


def main():
    source_points = set(TTFont(SOURCE).getBestCmap())
    # Dense CJK blocks stay small; sparse extension/symbol blocks are wider to
    # avoid producing hundreds of tiny downloads. No rule depends on page copy.
    groups = {}
    for point in sorted(source_points):
        if point <= 0x024F:
            key = "latin"
        else:
            width = 256 if 0x4E00 <= point <= 0x9FFF else 4096
            if point >= 0x10000:
                width = 65536
            key = f"u{point // width * width:04x}"
        groups.setdefault(key, []).append(point)

    OUTPUT.mkdir(parents=True, exist_ok=True)
    faces = ["// Generated by yarn build:fonts. Do not edit manually.\n"]
    shards = []
    covered = set()
    for key, points in groups.items():
        font = TTFont(SOURCE, recalcTimestamp=False)
        options = subset.Options()
        options.flavor = "woff2"
        options.layout_features = ["*"]
        options.name_IDs = ["*"]
        options.name_languages = ["*"]
        options.name_legacy = True
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=points)
        subsetter.subset(font)
        font.flavor = "woff2"
        temporary = OUTPUT / f"{key}.woff2"
        font.save(temporary)
        # Verify the actual encoded font, not just the requested character list.
        actual = set(TTFont(temporary).getBestCmap())
        if actual != set(points) or covered & actual:
            raise RuntimeError(f"Invalid or overlapping character coverage: {key}")
        covered.update(actual)
        checksum = digest(temporary)
        filename = f"unboundedsans-{key}.{checksum[:12]}.woff2"
        temporary.replace(OUTPUT / filename)
        ranges = unicode_ranges(points)
        url = f"https://assets.anuluca.com/fonts/unbounded/{filename}?v={digest(SOURCE)[:12]}"
        shards.append({"file": filename, "sha256": checksum, "codepoints": points,
                       "unicodeRange": ranges, "url": url})
        faces.append(
            "@font-face {\n"
            "  font-family: 'UnboundedSans';\n"
            f"  src: url('{url}') format('woff2');\n"
            "  font-style: normal;\n"
            "  font-weight: 400 900;\n"
            "  font-display: swap;\n"
            f"  unicode-range: {ranges};\n"
            "}\n"
        )
    if covered != source_points:
        raise RuntimeError("Source characters were lost during splitting")

    STYLESHEET.write_text("\n".join(faces), encoding="utf-8")
    # Update preload together with the content-addressed Latin filename.
    import re
    index = ROOT / "index.html"
    html = re.sub(
        r'href="[^"\s]*unboundedsans-latin[^"\s]*"',
        f'href="{shards[0]["url"]}"', index.read_text(encoding="utf-8")
    )
    index.write_text(html, encoding="utf-8")
    manifest = {"sourceSha256": digest(SOURCE), "sourceCodepoints": sorted(source_points),
                "stylesheetSha256": digest(STYLESHEET), "shards": shards}
    (OUTPUT / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    shutil.copyfile(ROOT / "scripts/fonts/OFL.txt", OUTPUT / "OFL.txt")
    current_files = {shard["file"] for shard in shards}
    for path in OUTPUT.glob("*.woff2"):
        if path.name not in current_files:
            path.unlink()
    total = sum((OUTPUT / name).stat().st_size for name in current_files)
    print(f"Verified {len(covered)} characters in {len(shards)} shards ({total:,} bytes)")


if __name__ == "__main__":
    main()
